### NumPy 실습 문제

### 문제 1.

길이가 10인 0-벡터(모든 요소가 0인)를 만드세요.



In [ ]:
import numpy as np

x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 문제 2.

길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.



In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

문제 3.

10 부터 49까지의 값을 가지는 벡터를 만드세요.



In [ ]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

문제 4.

위 벡터의 순서를 바꾸세요.



In [ ]:
x = np.arange(50, 9, -1)
x

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

문제 5.

0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.



In [ ]:
x = np.reshape(np.arange(9), (3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

문제 6.

벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.



In [ ]:
x = np.array([1,2,0,0,4,0])

x[x != 0]

array([1, 2, 4])

문제 7.

3x3 단위 행렬(identity matrix, 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인)을 만드세요



In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

문제 8.

난수 원소를 가지는 3x3 행렬을 만드세요



In [ ]:
x = np.random.rand(3,3)
x

array([[0.09471549, 0.55279204, 0.01033784],
       [0.43000656, 0.43208176, 0.76489639],
       [0.12079269, 0.10368301, 0.14864156]])

문제 9.

위에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.



In [ ]:
print(x.min(), x.max())


0.010337841482935373 0.7648963933902193


문제 10.

위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [ ]:
print(np.mean(x, axis = 1)) # 행평균
print(np.mean(x, axis = 0)) # 열평균

[0.21928179 0.54232824 0.12437242]
[0.21517158 0.36285227 0.3079586 ]
